### ISSUE TITLE
Failed to sync back

### ISSUE THREAD

**Issue by adouzzy** [neilagabriel/vim-geeknote#7] opened 2014-10-07 03:24 UTC
open a note, add a few lines. 
:w to save the file. close the file then run GeeknoteSync
Open Evernote, sync, no updates on the note.
open vim, sync, those few lines disappears.

Plus opening Geeknote in vim is very slow, and freezes the vim.
Nice work though.

**Comment by martijn** [comment] 2015-01-05 12:20
I have the same issue on Yosemite. Syncing sometimes failes silently. The workflow is simple; open a Note through the :Geeknote tree, work on it for ~10 minutes and save using :w. While vim is still open, sync the Evernote desktop client to see the note was not updated. Workaround for me is: write the note to a temporary file, restart vim, reopen the note and read in the temp file, save using :w. Then the changes are synced immediately.

Regardless of this particular issue, it would be nice if vim-geeknote could somehow give feedback when syncing is done so I don't have to check it manually before quitting vim. There are other issues that could cause syncing to fail (like network issues).

**Comment by neilagabriel** [comment] 2015-01-05 15:19
Thanks! I see one potential problem. Vim-geeknote uses temp files for everything you see. When opening a note I create a new temp file, write the note content to it, and the close the file handle. The last part seems problematic. Maybe Yosemite is aggressive about cleaning up temp files? Even if the file were deleted behind vim's back though, things should still work but maybe it throws the events off. Let me see if I can make the code smarter about when it releases the file.

**Comment by neilagabriel** [comment] 2015-01-05 19:29
Martijn,

Thinking about this more, I don't think the OS should delete any temp files while they are still in use. So my last comment probably doesn't apply. Once the plugin opens the file in a new buffer, there should exist an open filehandle for it.

However, even if the OS/filesystem did delete the file while it's in use, I still think everything should work. As an experiment, I manually deleted the temp file for a note while it was opened, then modified and saved it. That worked fine. So maybe I'm wrong to think that this issue has something to do with filesystem garbage collection. However, that leaves me without any other leads. vim-geeknote does not have any sort of background process so it should not be affected by time.

To be sure, I just pushed a change to my `dev` branch that allows you to specify where the plugin should create temp files. If you are willing, please pull the branch down (again, `dev` not `master`) and add the following to your .vimrc:

    let g:GeeknoteScratchDirectory=path

Note that the `path` must exist. Pointing it away from the system temp directory should ensure that the OS doesn't touch it.

Additionally, it may also be helpful if you add the following option to your vim command-line:

    -V9myVimLog

(or whatever the macvim equivalent is)

This will create a file named `myVimLog` in your CWD that will be written with all sorts of useful debug information. **Note that the log is very verbose so be sure to look at it before sending it to make sure it doesn't contain any sensitive information.**

Thanks

**Comment by martijn** [comment] 2015-01-12 11:04
Sorry didn't see this before. Will try soon!

**Comment by JadingTsunami** [comment] 2015-01-20 06:39
I think I know what's going on in adouzzy's case. If you set autochdir, you get the same behavior he describes -- the write succeeds, but Evernote is not updated. I haven't had a chance to look into why.

**Comment by neilagabriel** [comment] 2015-01-20 16:06
@JadingTsunami  Thanks for the information. Unfortunately, even with ```autochdir``` set, I'm still unable to reproduce this issue on Ubuntu. You are implying then that you're able to save/modify notes when ```autochdir``` is *not* set?

By the way, this plugin does rely on temporary files quite heavily. However, they are all created in the system's temp directory using an absolute path and from then on referenced using file handles. It would be very interesting to me to see how that could be affected by ```autochdir```.

**Comment by JadingTsunami** [comment] 2015-01-21 05:40
@neilagabriel Yep, that's what I see.

Here's what I'm doing (Mac OS X, clean install of [MacVIM, snapshot 73](https://github.com/b4winckler/macvim/releases)):
1. Launch vim with no vimrc, no plugins (`vim -u NONE -N`)
2. `:source` Geeknote plugin
3. Run `:Geeknote`
4. Edit an existing note.
5. `:w`
6. `:set autochdir`
7. Edit the note some more.
8. `:w`

The edits in step 4 will appear in Evernote. The edits from step 7 will not.

The behavior is the same if I start with `autochdir` set via my vimrc. I'd be curious if @adouzzy can reproduce this behavior as well.

**Comment by JadingTsunami** [comment] 2015-01-21 05:59
Got it - the problem is the autocommand pattern ends up being the full path name. When the directory is switched, the pattern match fails. Using `os.path.basename()`, when calling `autocmd()` looks like it fixes this (example below).

For instance:
    vim-geeknote/plugin/view.py:151
    autocmd('BufWritePre', 
            os.path.basename(f.name), # supply only filename
            ':call Vim_GeeknotePrepareToSaveNote("{}")'.format(f.name))

**Comment by neilagabriel** [comment] 2015-01-21 16:42
Wow, great! Thank you so much for investigating this. I'll get the fix in immediately.

**Comment by neilagabriel** [comment] 2015-01-21 17:16
Should be fixed in d7da44ff4cf848148345d536df2d5e9163e7a5b7. Could you please pull down the latest and try?

Note that I implemented the fix in a slightly different way. Instead of using the file's basename as the autocmd pattern I simply created a buffer-specific autocmd. That way the command is tied to the buffer instead of the name of the buffer.

**Comment by JadingTsunami** [comment] 2015-01-22 03:33
Works great! I like your fix; I think that's the right way to do this.

It does bother me, though - vim is documented to follow symlinks when resolving autocommands. It doesn't seem to be doing that.

**Comment by neilagabriel** [comment] 2015-01-22 04:50
Great. I agree that there is something fishy going on with vim in this regard. Since I was never able to reproduce it on Ubuntu, even with autochdir, maybe its a MacVim port issue? At any rate, thanks again for the help. I couldn't have figured it out without your help. I'm going to close this issue for now. @adouzzy please reopen it (or create a new bug) if you're still having issues.

**Closed by neilagabriel** 2015-01-22 04:50 UTC

**Comment by 7Moses** [comment] 2017-02-12 17:47
On a Mac, Using Yosemite 10.10.5, Just a Vim user, not MacVim; with Geeknote, I get a write confirmation but no sync with w, wq  ...  I like the idea of Geeknote, Best,
